"""
convert_team_images.py

Converts your 5 team photos into raw RGB565 pixel arrays baked into a
C header file, so the ESP32 can draw them directly to the ST7735 screen
with drawRGBBitmap() -- no WiFi, no JPEG decode, no network round-trip.

HOW TO USE (step by step):
1. Put your 5 real photos in the SAME folder as this script.
   Any image size/format is fine (jpg or png) -- this script will
   center-crop and resize them automatically. You do NOT need to resize
   them yourself first.
2. If your photo filenames don't match the ones listed in TEAM_PHOTOS
   below, either rename your photos to match, OR edit the filenames in
   TEAM_PHOTOS to match your actual files.
3. Run:  python convert_team_images.py
4. It creates a file called team_images.h in this same folder.
5. Copy (or move) team_images.h into the folder where jarvis_esp32.ino
   lives -- it MUST sit right next to the .ino file, Arduino won't find
   it in a subfolder or a different location.
6. Open jarvis_esp32.ino in the Arduino IDE and re-upload ("Flash") it
   to the ESP32, same as you normally do.
7. Say "who made you" to Jarvis -- the 5 photos should now show on the
   robot's screen instantly, with no WiFi needed for the images.
"""

from PIL import Image
import os

# Left side = photo filename to look for in this folder.
# Right side = the C variable name jarvis_esp32.ino expects.
# Edit the LEFT side only if your filenames are different.
TEAM_PHOTOS = {
    "meet.jpg":   "meet_img",
    "bhakti.jpg": "bhakti_img",
    "shreya.jpg": "shreya_img",
    "dhara.jpg":  "dhara_img",
    "janvi.jpg":  "janvi_img",
}

# Must match the ST7735 screen size used in jarvis_esp32.ino
# (showHardcodedProfile draws at 128x128). Don't change this number
# unless you also change the .ino code that draws it.
OUTPUT_SIZE = 128


def image_to_rgb565_values(path: str, size: int = OUTPUT_SIZE):
    img = Image.open(path).convert("RGB")

    # Center-crop to a square first, so resizing doesn't stretch/squish
    # faces if the original photo isn't already square.
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    img = img.resize((size, size), Image.LANCZOS)

    values = []
    for (r, g, b) in img.getdata():
        # Pack 8-bit RGB into 16-bit RGB565 (5 bits red, 6 green, 5 blue)
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        values.append(rgb565)
    return values


def main():
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by convert_team_images.py -- do not edit by hand.",
        "// Re-run the script and re-copy this file if you change any photos.",
        "",
    ]

    found_any = False
    for filename, varname in TEAM_PHOTOS.items():
        if not os.path.exists(filename):
            print(f"WARNING: '{filename}' not found in this folder -- skipping {varname}.")
            print("         (Rename your photo to match, or edit TEAM_PHOTOS in this script.)")
            continue

        found_any = True
        print(f"Converting {filename} -> {varname} ...")
        values = image_to_rgb565_values(filename)

        lines.append(f"const uint16_t {varname}[{len(values)}] = {{")
        for i in range(0, len(values), 16):
            chunk = values[i:i + 16]
            lines.append("  " + ", ".join(str(v) for v in chunk) + ",")
        lines.append("};")
        lines.append("")

    if not found_any:
        print("\nNo photos were found at all -- team_images.h was NOT created.")
        print("Check that your 5 photos are in this same folder and match TEAM_PHOTOS filenames.")
        return

    with open("team_images.h", "w") as f:
        f.write("\n".join(lines))

    print("\nDone! Created team_images.h in this folder.")
    print("Next: copy team_images.h into the SAME folder as jarvis_esp32.ino, then re-flash the ESP32.")


if __name__ == "__main__":
    main()